-- 추가 : 부모 자식 중 부모에게 먼저 추가를 해야한다.--

SELECT FLOWERNAME, FLOWERCOLOR,FLOWERPRICE FROM FLOWER;

SELECT * FROM FLOWER;

INSERT INTO FLOWER
(FLOWERNAME , FLOWERCOLOR , FLOWERPRICE)
VALUES ('장미','RED',3000);

INSERT INTO FLOWER
(FLOWERNAME , FLOWERCOLOR , FLOWERPRICE)
VALUES ('해바라기','YELLOW',3000);

INSERT INTO FLOWER
(FLOWERNAME , FLOWERCOLOR , FLOWERPRICE)
VALUES ('할미꽃','WHITE',9000);

SELECT * FROM POT;

INSERT INTO POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20211207001', 'WHITE', '물레방아', '장미');

INSERT INTO HR.POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20211207002', 'BLACK', '타원형', '해바라기');

INSERT INTO HR.POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20211207004', 'RED', '타원형', '할미꽃');

-- 참조하고있는 자식테이블에서 먼저 삭제해야함--

DELETE FROM FLOWER
WHERE FLOWERNAME = '장미';

DELETE FROM POT
WHERE NAME = '장미';

-- delete 와 truncate 의 차이
-- delete  : 복구가 가능
-- truncate : 복구 불가

UPDATE POT
SET POTCOLOR = 'WHITE'
WHERE NAME = '할미꽃' AND POTSHAPE ='타원형';

-------------------------------------------------------------------------------
--day08-3 DML1 , 데이터 내보내기

SELECT * FROM OWER;
SELECT * FROM PET;

INSERT INTO OWER
(ID,NAME,AGE,ADDRESS)
VALUES ('20211207','홍길동',20,'경기도 남양주시');

UPDATE OWER
SET ID = '20211207001'
WHERE NAME='홍길동';

INSERT INTO OWER
(ID,NAME,AGE,ADDRESS)
VALUES ('20211207002','이순신',30,'경상남도 진주시');

INSERT INTO PET
(PIN,NAME,AGE,OWERID,GENDER)
VALUES ('8202001','뽀삐',4,'20211207001','W');

INSERT INTO PET
VALUES('8002002','바둑이',3,'20211207002','M');

INSERT INTO PET
VALUES('8002003','야옹이',10,'20211207002','M');


SELECT * FROM PET WHERE GENDER != 'M';

SELECT NAME FROM PET WHERE GENDER = 'W';

DELETE FROM PET
WHERE NAME='바둑이';

UPDATE OWER
SET NAME = '김유신'
WHERE ID = '20211207002';

TRUNCATE TABLE PET;

SELECT * FROM PET;
