/*
 * OWER
 * ID VC2(200)
 * -----------------
 * NAME VC2(200)
 * AGE N(5)
 * ADDRESS VC2(300)
 * 
 * PET
 * PIN VC2(300)
 * ---------------
 * NAME VC2(200)
 * AGE N(5)
 * OWERID VC2(200)) FK
 */

CREATE TABLE OWER(
	ID VARCHAR2(200) PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	AGE NUMBER(5) DEFAULT 20,
	ADDRESS VARCHAR2(300)
);

DROP TABLE OWER;
SELECT * FROM OWER;

CREATE TABLE PET(
	PIN VARCHAR2(300) PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	AGE NUMBER(5) DEFAULT 1,
	OWERID VARchar2(200),
	CONSTRAINT PET_FK FOREIGN KEY(OWERID) REFERENCES OWER(ID);
	
);

