CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(100),
	COLOR VARCHAR2(100),
	PRICE NUMBER(10),
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

SELECT * FROM TBL_CAR;

DROP TABLE CAR;

ALTER TABLE TBL_CAR MODIFY BRAND NOT NULL;
ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C007040;

SELECT * FROM PLAYER
WHERE "POSITION" IS NULL;

SELECT * FROM PLAYER
WHERE "POSITION" IS NOT NULL;

