--SCOTT 계정의 EMP 테이블을 복사해서 비등가 조인으로 ENAME, SAL 검색하기
CREATE TABLE EMP AS SELECT * FROM SCOTT.EMP;

--비등가 조인
SELECT S."LEVEL", E.ENAME,E.SAL FROM EMP E JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL ORDER BY 1;

--HR 계정의 DEPT 테이블을 복사, 복사한 테이블에서 LOC별 평균 급여 검색(단, LOC은 모두 검색)
CREATE TABLE COPY_DEPT AS SELECT * FROM HR.DEPT;
CREATE TABLE COPY_EMP AS SELECT * FROM HR.EMP;

SELECT LOC,NVL(AVG(E.SAL),0) 평균급여 FROM COPY_DEPT D LEFT OUTER JOIN COPY_EMP E
ON D.DEPTNO = E.DEPTNO
GROUP BY LOC;

SELECT * FROM COPY_DEPT; 