--EMPLOYEES 테이블에서 HIREDATE가 2003~2005년까지인 사원 검색
-- HIREDATE , FIRST_NAME , DEPARTMENT_NAME
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT HIRE_DATE , FIRST_NAME , DEPARTMENT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
--2005년 12월로 하면 12월 자체가 포함되지 않기떄문에 06년1월로 한다.
AND HIRE_DATE BETWEEN TO_DATE('2003-01','YYYY-MM') AND TO_DATE('2006-01','YYYY-MM'); 

--네츄럴 조인(NATURAL JOIN) , 2가지 방법이 있음
--중복되는 컬럼이 생길 시 맨 앞으로 출력하며 중복 컬럼을 한개만 출력한다, 컬럼 이름 뿐만 아니라 타입이 모두 같아야 한다.
-- USING() : 
SELECT * FROM EMP E INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

--방법1
SELECT * FROM EMP E INNER JOIN DEPT D
USING(DEPTNO);

--방법 2
SELECT * FROM EMP E NATURAL JOIN DEPT D;


--외부 조인(OUTER JOIN)
-- 두 개의 테이블 중 조건이 거짓이라도 지정한 테이블의 모든 정보가 검색되어야할 때 사용

--LEFT OUTER JOIN
SELECT * FROM STADIUM;
SELECT * FROM TEAM;

SELECT * FROM STADIUM LEFT OUTER JOIN TEAM
ON HOMETEAM_ID = TEAM_ID;

--RIGHT OUTER JOIN
SELECT * FROM TEAM RIGHT OUTER JOIN STADIUM
ON HOMETEAM_ID = TEAM_ID;

--FULL OUTER JOIN
SELECT * FROM TEAM FULL OUTER JOIN STADIUM
ON HOMETEAM_ID = TEAM_ID;

--SELF JOIN
SELECT * FROM EMP;

SELECT E1.ENAME "사원", E2.ENAME "매니저" FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO;













